language: c
compiler:
  - gcc
  - clang

sudo: false

script:
  - pushd build && cmake .. && make && popd
  - pushd build && cmake -DENABLE_SHARED=1 .. && make && popd

notifications:
  email:
    on_success: never
    on_failure: always
